### ISSUE TITLE
When will the dataset be available?

### ISSUE THREAD

**Issue by Pixie412** [SaschaHornauer/Batvision#1]
Dear authors,
Thanks for sharing the code! I am wondering when the dataset will be released?

**Comment by Cratial** [comment]
Ha, it's not available still on 13 Jul., 2021.

**Comment by SaschaHornauer** [comment]
Sorry for the heavy delay. This is not forgotten. Main people like myself went to other positions in other institutions lacking the time to work on this. We need to make sure the data complies to the GDPR ( basically just cut out accidentally filmed people ) among other technical things. I hope we finish everything by October. Again, sorry for the delay.

**Comment by SaschaHornauer** [comment]
We just released all the data and added some additionally to make up for the long wait. Please check out the main Readme on how to download everything.

**Comment by SaschaHornauer** [comment]
We just released all the data and added some additionally to make up for the long wait. Please check out the main Readme on how to download everything.
